### ISSUE TITLE
[报错] 本地部署访问链接时返回报错

### ISSUE THREAD

**Issue by FxRayHughes** [Lete114/WebStack-Screenshot#1]
Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (961656).
    at ChromeLauncher.launch (D:\mirai\WS\WebStack-Screenshot\node_modules\puppeteer\lib\cjs\puppeteer\node\Launcher.js:101:23)
    at async Server.module.exports (D:\mirai\WS\WebStack-Screenshot\src\main.js:30:15)

{"msg":"Screenshot failed"}

**Comment by lete114** [comment]
执行了`npm install`了吗？
因该是没有成功安装chromium
