### ISSUE TITLE
vercel 部署报错

### ISSUE THREAD

**Issue by romoo** [Lete114/WebStack-Screenshot#12]
1. 使用 `Vercel` 分支部署 vercel.com，运行时报错：

```
NODE.js v18.18.2
Error: Could not find Chrome (ver. 119.0.6045.105). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npx puppeteer browsers install chrome`) or
 2. your cache path is incorrectly configured (which is: /home/sbx_user1051/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:278:27)
    at ChromeLauncher.executablePath (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:209:25)
    at PuppeteerNode.executablePath (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/PuppeteerNode.js:160:31)
    at launch (/var/task/node_modules/webstack-screenshot/dist/src/utils.js:100:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.default (/var/task/node_modules/webstack-screenshot/dist/src/main.js:19:27)
    at async module.exports (/var/task/node_modules/webstack-screenshot/dist/src/serverless.js:23:25)
    at async Server.<anonymous> (/opt/node-bridge/helpers-UZ7RIBE7.js:1:7888)
    at async Server.<anonymous> (/opt/node-bridge/bridge-server-NOEMJORR.js:1:8898)
```

2. 修改项目 Build Command 为 `npx puppeteer browsers install chrome`，Build 时报错：

```
Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings.
```

3. 手动添加 `public` 目录后，运行时报错与 1 相同

**Comment by lete114** [comment]
已修复，感谢你的反馈 :)
