### ISSUE TITLE
您好，请问可以添加个指定chromium路径吗

### ISSUE THREAD

**Issue by valetzx** [Lete114/WebStack-Screenshot#2]
报错为：
```
Service is up and running port: 6870
Error: Failed to launch the browser process!
/home/runner/websnap/node_modules/puppeteer/.local-chromium/linux-961656/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/home/runner/websnap/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:237:20)
    at Interface.<anonymous> (/home/runner/websnap/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:227:68)
    at Interface.emit (node:events:402:35)
    at Interface.close (node:readline:586:8)
    at Socket.onend (node:readline:277:10)
    at Socket.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by lete114** [comment]
目前还未支持自定义chromium

**Comment by lete114** [comment]
已支持自定义chromium路径，路径填写再环境变量中的`PUPPETEER_EXECUTABLE_PATH`
